languageCode = "en-us"
title = "Ciaran De Groot"
theme = [
  "hugo-admonitions", # just adds support for Markdown callouts
  "hugo-theme-anubis", # the actual theme
]

[menu]

    [[menu.main]]
    name = "about"
    url = "/"
    weight = -140

    [[menu.main]]
    name = "gallery"
    url = "/gallery/"
    weight = -130

    [[menu.main]]
    name = "blog"
    url = "/blog/"
    weight = -120

    #[[menu.main]]
    #name = "contact"
    #url = "/contact/"
    #weight = -100

[permalinks]
posts = "/archive/:filename"

[taxonomies]
tag = "tags"

[params]
assets_bucket_url = "https://ciarandg-portfolio.us-southeast-1.linodeobjects.com"
